id = "php"
name = "PHP"
description = "PHP support."
version = "0.3.0"
schema_version = 1
authors = ["Piotr Osiewicz <piotr@zed.dev>"]
repository = "https://github.com/zed-extensions/php"

[language_servers.phptools]
name = "PhpTools"
language = "PHP"
language_ids = { PHP = "php" }

[language_servers.intelephense]
name = "Intelephense"
language = "PHP"
language_ids = { PHP = "php" }

[language_servers.phpactor]
name = "Phpactor"
language = "PHP"

[debug_adapters.Xdebug]

[grammars.php]
repository = "https://github.com/tree-sitter/tree-sitter-php"
commit = "8ab93274065cbaf529ea15c24360cfa3348ec9e4"
path = "php"

[grammars.phpdoc]
repository = "https://github.com/claytonrcarter/tree-sitter-phpdoc"
commit = "03bb10330704b0b371b044e937d5cc7cd40b4999"
