id = "php"
name = "PHP"
description = "PHP support."
version = "0.4.8"
schema_version = 1
authors = ["Piotr Osiewicz <piotr@zed.dev>"]
repository = "https://github.com/zed-extensions/php"

[language_servers.phptools]
name = "PhpTools"
language = "PHP"
language_ids = { PHP = "php" }

[language_servers.intelephense]
name = "Intelephense"
language = "PHP"
language_ids = { PHP = "php" }

[language_servers.phpactor]
name = "Phpactor"
language = "PHP"

[debug_adapters.Xdebug]

[grammars.php]
repository = "https://github.com/tree-sitter/tree-sitter-php"
commit = "5b5627faaa290d89eb3d01b9bf47c3bb9e797dea"
path = "php"

[grammars.phpdoc]
repository = "https://github.com/claytonrcarter/tree-sitter-phpdoc"
commit = "488198e61f49fc74ee54069a4126b556665a57cc"
